### ISSUE TITLE
In multi-valued input the maximum number of fields is limited to 2

### ISSUE THREAD

**Issue by phochste** [danielbeeke/frm#1]
**Try**

- Run the demo
- Add a family name with the (+)
- Add another family name with the (+)

**Expected**

- Three family name fields

**Got**

- Two family name fields
- The (+) sign is missing to add more
- The new second family name can't be deleted

**Comment by danielbeeke** [comment]
This might have been because I have strange values in the SHACL for testing. I can not reproduce now.
