### ISSUE TITLE
Date field year can't be edited

### ISSUE THREAD

**Issue by phochste** [danielbeeke/frm#2]
**Try**

- Start the demo
- Set the BirthDate field to 1971

**Expected**

- The value '1971'

**Got**

- In some case '0019' in other cases a second or even third BirthDate field with '0071' (even when the field isn't multi-valued)
- The date popup doesn't show

**Comment by phochste** [comment]
I use Vivaldi 5.3.2679.68 (Stable channel) (x86_64) on OSX. In this browser I don't see the date picker. And when I try to set the date by typing I get this strange effect of creating extra data fields.

I tried it on Chrome and also there I don't see the date picker and the weird effects when setting a date manually.

In Firefox I see the date picker, but can't set the date manually.

In Safari I see the date picker, but can't set the date manually.

**Comment by danielbeeke** [comment]
I found what goes wrong. I will debug it.
