### ISSUE TITLE
Can you provide an example how to capture the result of the submit button?

### ISSUE THREAD

**Issue by phochste** [danielbeeke/frm#3]
I now had to uncomment these lines: https://github.com/danielbeeke/frm/blob/main/src/CustomElements/FrmForm.ts#L83
But I guess you plan some event that can be triggered from the frm-form?

Like [?]:
```
<frm-form 
   ...
   onsubmit={..javascript...}
/>
```

**Comment by danielbeeke** [comment]
added an event
